FROM golang:1.25-alpine AS builder
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN go test ./...
RUN CGO_ENABLED=0 go build -o /usr/local/bin/greeter ./cmd/greeter

FROM scratch
COPY --from=builder /usr/local/bin/greeter /usr/local/bin/greeter
USER 65532:65532
CMD ["/usr/local/bin/greeter"]

